Issue
  { issueClosedAt = Just 2016 (-07) (-20) 23 : 10 : 30 UTC
  , issueUpdatedAt = 2016 (-07) (-20) 23 : 10 : 30 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/1154/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/docs/issues/1154"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 1154
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 467928
          , simpleUserLogin = N "chipotle"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/467928?v=3"
          , simpleUserUrl = "https://api.github.com/users/chipotle"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 1777134
        , simpleUserLogin = N "mlucy"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1777134?v=3"
        , simpleUserUrl = "https://api.github.com/users/mlucy"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "https://www.rethinkdb.com/api/javascript/each_async/ has an incorrect example"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/1154"
  , issueCreatedAt = 2016 (-07) (-10) 02 : 18 : 00 UTC
  , issueBody =
      Just
        "One of the examples writes `return 'Bad row: ' + row`.  This isn't actually allowed, it should be `throw new Error('Bad row: ' + row)`."
  , issueState = "closed"
  , issueId = Id 164695435
  , issueComments = 0
  , issueMilestone = Nothing
  }