Issue
  { issueClosedAt = Just 2015 (-08) (-12) 22 : 12 : 31 UTC
  , issueUpdatedAt = 2015 (-08) (-12) 22 : 12 : 31 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/853/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/docs/issues/853"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 853
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 467928
          , simpleUserLogin = N "chipotle"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/467928?v=3"
          , simpleUserUrl = "https://api.github.com/users/chipotle"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 1366
        , simpleUserLogin = N "deontologician"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1366?v=3"
        , simpleUserUrl = "https://api.github.com/users/deontologician"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "Link to python `type_of` docs from api sidebar is broken"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/853"
  , issueCreatedAt = 2015 (-08) (-12) 22 : 06 : 31 UTC
  , issueBody =
      Just
        "Looks like the f is cut off, it links to:\r\n\r\nhttp://docs.rethinkdb.com/2.1/api/python/type_o\r\n\r\nThe ruby and js versions seem to have the right link"
  , issueState = "closed"
  , issueId = Id 100645587
  , issueComments = 0
  , issueMilestone = Nothing
  }