IssueComment
  { issueCommentUpdatedAt = 2014 (-06) (-23) 14 : 31 : 41 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 1461947
        , simpleUserLogin = N "neumino"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1461947?v=3"
        , simpleUserUrl = "https://api.github.com/users/neumino"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/comments/46852499"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/docs/issues/155#issuecomment-46852499"
  , issueCommentCreatedAt = 2014 (-06) (-23) 14 : 31 : 41 UTC
  , issueCommentBody =
      "If I'm not mistaken, one tricky part of this issue is that one server will report an \"unavailable server\", while the other one will think that everything works fine.\r\n\r\n@coffeemug describes the real use case.\r\nWhat happens most of the time is people trying RethinkDB and connecting their laptop to a real server that lies on another network."
  , issueCommentId = 46852499
  }